### ISSUE TITLE
gdata

### ISSUE THREAD

**Issue by shahzebsiddiqui** [shahzebsiddiqui/R-buildtest-config#130]
https://cran.r-project.org/web/packages/gdata/gdata.pdf

**Comment by singh-vijay** [comment]
https://github.com/shahzebsiddiqui/R-buildtest-config/commit/317375baf53b5397dbf947537b94358f709a7ff7

**Comment by singh-vijay** [comment]
https://github.com/shahzebsiddiqui/R-buildtest-config/commit/bd48ae5bd6ba467d8f6d33d909e3cdc6b2b2d4fe
