### ISSUE TITLE
acepack

### ISSUE THREAD

**Issue by shahzebsiddiqui** [shahzebsiddiqui/R-buildtest-config#4]
https://cran.r-project.org/web/packages/acepack/acepack.pdf

**Comment by singh-vijay** [comment]
https://github.com/shahzebsiddiqui/R-buildtest-config/commit/b2af7d55b73d31b9e2c2dafa587479135c5161c5

https://github.com/shahzebsiddiqui/R-buildtest-config/commit/53a88835a2e64c2d0bb4bc78e41bb2c6394c4d4f
